import React from "react";
import ArtistList from "./ArtistList";
import Header from "../Components/Header";
import type { Metadata } from "next";
import { PageWrapper } from "../Components/PageWrapper";

export const metadata: Metadata = {
  title: "Artists",
  description: "Generated by create next app",
};

type Props = {};

const ArtistsPage = (props: Props) => {
  return (
    <main className="min-h-screen">
      <PageWrapper>
      <Header>
        <h1 className="text-5xl font-bold font-oswald text-center">
          Featured Artists
        </h1>
      </Header>
      <ArtistList />
      </PageWrapper>
    </main>
  );
};

export default ArtistsPage;
